services:
  glue:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
#    build:
#      context: .   # Use current directory as the build context
#      dockerfile: Dockerfile  # Specify the Dockerfile
#    image: glue-dev-img  # Custom Glue image name
    container_name: glue
    environment:
      - AWS_PROFILE=default
      - AWS_REGION=us-east-1
      - DISABLE_SSL=true
    volumes:
      - /home/dasarrathi/.aws:/home/glue_user/.aws
#      - ${WORKSPACE_LOCATION}:/home/glue_user/workspace/
      - ./workspace:/home/glue_user/workspace/
      - ./data:/home/glue_user/data
      - ./logs:/home/glue_user/logs
    ports:
      - "4040:4040"
      - "18080:18080"
      - "8998:8998"
      - "8888:8888"
#    command: >
#      spark-submit /home/glue_user/workspace/${SCRIPT_FILE_NAME}
    stdin_open: true
    tty: true
    restart: always
